apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnscrypt
spec:
  selector:
    matchLabels:
      app: dns-server
      component: dnscrypt
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: dns-server
        component: dnscrypt
    spec:
      containers:
        - name: dnscrypt
          image: publicarray/dnscrypt-wrapper
          command: ["/entrypoint.sh", "start"]
          ports:
            - name: dns
              containerPort: 443
          volumeMounts:
            - name: dnscrypt
              mountPath: /opt/dnscrypt
      restartPolicy: Always
      volumes:
        - name: dnscrypt
          hostPath:
            path: /data/dnscrypt
            type: DirectoryOrCreate
