apiVersion: v1
kind: Service
metadata:
  name: dnscrypt
  labels:
    app: dns-server
    component: dnscrypt
spec:
  selector:
    app: dns-server
    component: dnscrypt
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 443
      targetPort: 443
    - name: dns-udp
      protocol: UDP
      port: 443
      targetPort: 443
  type: NodePort
  # type: LoadBalancer
