apiVersion: batch/v1
kind: Job
metadata:
  name: dnscrypt-key-rotation
spec:
  template:
    metadata:
      name: dnscrypt-key-rotation
    spec:
      schedule: "*/30 * * * *"
      containers:
        - name: dnscrypt-key-rotation
          image: publicaray/dnscrypt-wrapper
          command:
            - /usr/local/sbin/anscript-auto
            - renew
          volumeMounts:
            - name: dnscrypt
              mountPath: /opt/dnscrypt
      restartPolicy: Never  # OnFailure
      volumes:
        - name: dnscrypt
          hostPath:
            path: /data/dnscrypt
            type: DirectoryOrCreate
