version: '3.2'
volumes:
    dnscrypt:
    ssl:
    nsd:
services:
  # watchtower:
  #   image: v2tec/watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - $DOCKER_CERT_PATH:/etc/ssl/docker
  #   command: --tlsverify
  acme:
    image: neilpang/acme.sh
    command: >
      /bin/sh -c "echo \"#!/bin/sh

      set -e

      if [ -f /opt/ssl/fullchain.pem ]; then
        if openssl x509 -checkend 2592000 -noout -in /opt/ssl/fullchain.pem; then
          echo 'Certificate is still valid!'
          exit 0
        else
          echo 'Certificate has expired or will do so within 30 days!'
          echo 'Renewing...'
        fi
      fi

      export CF_Key='$$(cat /run/secrets/CF_Key)'
      export CF_Email='$$(cat /run/secrets/CF_Email)'

      #### Remember to remove '--staging' in production! ####

      acme.sh
      --issue
      --dns dns_cf
      --dnssleep 60
      --domain doh.seby.io
      --domain cf-doh.seby.io
      --keylength 4096
      --fullchain-file /opt/ssl/fullchain.pem
      --key-file /opt/ssl/key.pem
      --ca-file /opt/ssl/ca.pem
      --cert-file /opt/ssl/cert.pem
      --reloadcmd 'cat /opt/ssl/key.pem > cat /opt/ssl/fullchain.pem > /opt/ssl/fullchain-key.pem.rsa'

      acme.sh
      --issue
      --dns dns_cf
      --dnssleep 60
      --domain doh.seby.io
      --domain cf-doh.seby.io
      --keylength ec-384
      --fullchain-file /opt/ssl/fullchain-ecc.pem
      --key-file /opt/ssl/key-ecc.pem
      --ca-file /opt/ssl/ca-ecc.pem
      --cert-file /opt/ssl/cert-ecc.pem
      --reloadcmd 'cat /opt/ssl/key-ecc.pem > cat /opt/ssl/fullchain-ecc.pem > /opt/ssl/fullchain-key.pem.ecdsa'
      \" > start.sh
      && chmod +x start.sh
      && ./start.sh"
    deploy:
      resources:
        limits:
          memory: 10M
        reservations :
          cpus: "0.2"
          memory: 4M
      restart_policy:
        condition: on-failure
        max_attempts: 4
    secrets:
      - CF_Email
      - CF_Key
    volumes:
       - ssl:/opt/ssl
  acme-daemon:
    image: neilpang/acme.sh
    command: daemon
    deploy:
      resources:
        limits:
          memory: 4M
        reservations :
          cpus: "0.2"
          memory: 4M
      restart_policy:
        condition: on-failure
        max_attempts: 4
    secrets:
      - CF_Email
      - CF_Key
    volumes:
       - ssl:/opt/ssl

  nsd:
    build: nsd
    image: publicarray/nsd
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 150M
        reservations:
          cpus: '0.1'
          memory: 100M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 4
    volumes:
      - nsd:/etc/nsd/run
    networks:
      - nsd-net

  unbound:
    depends_on:
      - nsd
    build: unbound
    image: publicarray/unbound
    command: -m -d
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 300M
        reservations :
          cpus: "0.2"
          memory: 250M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 4
    ports:
      - target: 4949
        published: 4949
        protocol: tcp
        mode: ingress
    networks:
      - nsd-net
      - unbound-net

  doh-proxy:
    depends_on:
      - unbound
    build: doh-proxy
    image: publicarray/doh-proxy
    command: -d
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
    networks:
      - unbound-net

  haproxy:
    depends_on:
      - acme
      - doh-proxy
      - unbound
    build: haproxy
    image: publicarray/haproxy
    command: -d -r
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 40M
        reservations :
          cpus: "0.2"
          memory: 20M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 4
    ports:
    - target: 443
      published: 443
      protocol: tcp
      mode: ingress
    - target: 853
      published: 853
      protocol: tcp
      mode: ingress
    volumes:
       - ssl:/opt/ssl
    networks:
      - haproxy-net
      - unbound-net

  dnscrypt-wrapper:
    depends_on:
      - unbound
    image: publicarray/dnscrypt-wrapper
    command:
      - init
      - -d
      - -N
      - dns.seby.io
      - -E
      - 149.28.165.94:8443
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 5M
        reservations :
          cpus: "0.2"
          memory: 4M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 4
    ports:
      - target: 443
        published: 8443
        protocol: tcp
        mode: ingress
      - target: 443
        published: 8443
        protocol: udp
        mode: ingress
    volumes:
       - dnscrypt:/opt/dnscrypt
    networks:
      - dnscrypt-net
      - unbound-net

secrets:
  CF_Email:
    external: true
  CF_Key:
    external: true

networks:
  dnscrypt-net:
    driver: overlay
  haproxy-net:
    driver: overlay
  nsd-net:
    driver: overlay
  unbound-net:
    driver: overlay
