apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  labels:
    service: nsd
  name: nsd
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: dns-server
        component: nsd
        service: nsd
    spec:
      containers:
        - env:
          image: publicarray/nsd
          name: nsd
          command: ["/entrypoint.sh"]
          resources:
            requests:
              memory: "1Gi"
      restartPolicy: Always
