apiVersion: apps/v1
kind: Deployment
metadata:
  name: doh-proxy
spec:
  selector:
    matchLabels:
      app: dns-server
      component: doh-proxy
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: dns-server
        component: doh-proxy
    spec:
      containers:
        - name: doh-proxy
          image: publicarray/doh-proxy
          # command: ["/entrypoint.sh"]
          ports:
            - name: dns
              containerPort: 3000
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 50Mi
      restartPolicy: Always
