apiVersion: v1
kind: Service
metadata:
  name: doh-proxy
  labels:
    app: dns-server
    component: doh-proxy
spec:
  selector:
    app: dns-server
    component: doh-proxy
  ports:
    - name: doh-tcp
      protocol: TCP
      port: 3000
      targetPort: 3000
  # type: ClusterIP
