apiVersion: v1
kind: Service
metadata:
  name: haproxy
  labels:
    app: dns-server
    component: haproxy
spec:
  selector:
    application: dns-server
    service: haproxy
  ports:
    - name: dns-over-tls-tcp
      protocol: TCP
      port: 853
      targetPort: 853
    - name: dns-over-tls-udp
      protocol: UDP
      port: 853
      targetPort: 853
    - name: doh-tcp
      protocol: TCP
      port: 443
      targetPort: 443
    - name: doh-udp
      protocol: UDP
      port: 443
      targetPort: 443
  type: NodePort
