apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  labels:
    service: haproxy
  name: haproxy
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: dns-server
        component: haproxy
        service: haproxy
    spec:
      containers:
        - env:
          image: publicarray/haproxy
          name: haproxy
          ports:
            - name: dns-over-tls
              containerPort: 853
            - name: doh
              containerPort: 453
          volumeMounts:
            - name: ssl
              mountPath: /opt/ssl
          # command: ["/usr/local/sbin/haproxy", "-f", "/etc/haproxy.conf"]
          # resources:
          #   requests:
          #     memory: "1Gi"
      restartPolicy: Always
      volumes:
        - name: ssl
          hostPath:
            path: /data/ssl
            type: DirectoryOrCreate
