apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  labels:
    service: haproxy
  name: haproxy
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: dns-server
        component: haproxy
        service: haproxy
    spec:
      containers:
        - env:
          image: publicarray/haproxy
          name: haproxy
          volumeMounts:
            - name: ssl-keys
              mountPath: /opt/ssl-keys
          command: ["/entrypoint.sh"]
          # resources:
          #   requests:
          #     memory: "1Gi"
      restartPolicy: Always
      volumes:
        - name: ssl-keys
          hostPath:
            path: /data/ssl-keys
            type: DirectoryOrCreate
