apiVersion: v1
kind: Service
metadata:
  name: haproxy-tcp
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 453
      targetPort: 453
  selector:
    service: haproxy
  type: LoadBalancer
  loadBalancerIP: 0.0.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-udp
  namespace: default
spec:
  ports:
    - protocol: UDP
      port: 453
      targetPort: 453
  selector:
    service: haproxy
  type: LoadBalancer
  loadBalancerIP: 0.0.0.0
