apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  labels:
    service: haproxy
  name: haproxy
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        service: dnscrypt
    spec:
      containers:
      - env:
        image: publicarray/haproxy
        name: ssl-keys
        volumeMounts:
          - name: ssl-keys
            mountPath: /opt/ssl-keys
        command: ["/entrypoint.sh"]
        resources:
          requests:
            memory: "1Gi"
      restartPolicy: Always
      volumes:
        - name: ssl-keys
          hostPath:
            path: /data/ssl-keys
            type: DirectoryOrCreate

