apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
spec:
  selector:
    matchLabels:
      app: dns-server
      component: unbound
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: dns-server
        component: unbound
    spec:
      containers:
        - name: unbound
          image: publicarray/unbound
          # command: ["/entrypoint.sh"]
          ports:
            - name: dns
              containerPort: 53
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
      restartPolicy: Always
