apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  labels:
    service: unbound
  name: unbound
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: dns-server
        component: unbound
        service: unbound
    spec:
      containers:
        - env:
          image: publicarray/unbound
          name: unbound
          command: ["/entrypoint.sh"]
          resources:
            requests:
              memory: "1Gi"
      restartPolicy: Always
