name: dnscrypt-server
on:
  push:
    paths:
      - 'dnscrypt-server/*'
jobs:
  build:
    name: Build & Push dnscrypt-server Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t publicarray/dnscrypt-server dnscrypt-server
      - uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: docker push publicarray/dnscrypt-server
      - uses: azure/container-actions/docker-logout@master
