name: dnscrypt-wrapper
on:
  push:
    paths:
      - 'dnscrypt-wrapper/*'
jobs:
  build:
    name: Build & Push dnscrypt-wrapper Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t publicarray/dnscrypt-wrapper dnscrypt-wrapper
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push publicarray/dnscrypt-wrapper
