name: dnscrypt-wrapper Workflow
on:
  push:
    paths:
      - 'dnscrypt-wrapper/*'
jobs:
  build:
    name: Build & Push dnscrypt-wrapper Container
    runs-on: ubuntu-latest
    steps:
      - name: Docker Registry
        uses: actions/docker/login@86ff551d26008267bb89ac11198ba7f1d807b699
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Action for dnscrypt-wrapper Docker
        uses: actions/docker/cli@86ff551d26008267bb89ac11198ba7f1d807b699
        with:
          args: build -t publicarray/dnscrypt-wrapper dnscrypt-wrapper && docker push publicarray/dnscrypt-wrapper
