name: dnscrypt-server
on:
  push:
    paths:
      - 'dnscrypt-server/*'
jobs:
  build:
    name: Build & Push dnscrypt-server Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login, Build and Push to Docker Registry
      - uses: azure/container-actions/docker-login@master
          with:
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
          - run: |
              docker build -t publicarray/dnscrypt-server dnscrypt-server
              docker push publicarray/dnscrypt-server
