name: dnscrypt-server
on:
  push:
    paths:
      - 'dnscrypt-server/*'
jobs:
  build:
    name: Build & Push dnscrypt-server Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t publicarray/dnscrypt-server dnscrypt-server

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.actor }}/dns-resolver-infra/dnscrypt-server
          # tag_with_ref: true

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.actor }}/dnscrypt-server
          # tag_with_ref: true
