name: doh-proxy
on:
  push:
    paths:
      - 'doh-proxy/*'
jobs:
  build:
    name: Build & Push doh-proxy Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t publicarray/doh-proxy doh-proxy

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.actor }}/dns-resolver-infra/doh-proxy
          # tag_with_ref: true

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.actor }}/doh-proxy
          # tag_with_ref: true
