name: doh-proxy
on:
  push:
    paths:
      - 'doh-proxy/*'
jobs:
  build:
    name: Build & Push doh-proxy Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t publicarray/doh-proxy doh-proxy
      - uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: docker push publicarray/doh-proxy
      - uses: azure/container-actions/docker-logout@master
