name: doh-proxy
on:
  push:
    paths:
      - 'doh-proxy/*'
jobs:
  build:
    name: Build & Push doh-proxy Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t publicarray/doh-proxy doh-proxy
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push publicarray/doh-proxy
