name: doh-proxy
on:
  push:
    paths:
      - 'doh-proxy/*'
jobs:
  build:
    name: Build & Push doh-proxy Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login, Build and Push to Docker Registry
      - uses: azure/container-actions/docker-login@master
          with:
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
          - run: |
              docker build -t publicarray/doh-proxy doh-proxy
              docker push publicarray/doh-proxy
