name: haproxy
on:
  push:
    paths:
      - 'haproxy/*'
jobs:
  build:
    name: Build & Push haproxy Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login, Build and Push to Docker Registry
      - uses: azure/container-actions/docker-login@master
          with:
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
          - run: |
              docker build -t publicarray/haproxy haproxy
              docker push publicarray/haproxy
