name: haproxy
on:
  push:
    paths:
      - 'haproxy/*'
jobs:
  build:
    name: Build & Push haproxy Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t publicarray/haproxy haproxy
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push publicarray/haproxy
