name: haproxy
on:
  push:
    paths:
      - 'haproxy/*'
jobs:
  build:
    name: Build & Push haproxy Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t publicarray/haproxy haproxy
      - uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.DOCKER_PASSWORD }}
          password: ${{ secrets.DOCKER_USERNAME }}
      - run: docker push publicarray/haproxy
      - uses: azure/container-actions/docker-logout@master
