name: haproxy
on:
  push:
    paths:
      - 'haproxy/*'
jobs:
  build:
    name: Build & Push haproxy Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t publicarray/haproxy haproxy

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.actor }}/dns-resolver-infra/haproxy
          # tag_with_ref: true

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.actor }}/haproxy
          # tag_with_ref: true
