name: m13253-doh
on:
  push:
    paths:
      - 'm13253-doh/*'
jobs:
  build:
    name: Build & Push m13253-doh Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t publicarray/m13253-doh m13253-doh
      - uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: docker push publicarray/m13253-doh
      - uses: azure/container-actions/docker-logout@master
