name: m13253-doh
on:
  push:
    paths:
      - 'm13253-doh/*'
jobs:
  build:
    name: Build & Push m13253-doh Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t publicarray/m13253-doh m13253-doh
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push publicarray/m13253-doh
