name: nsd
on:
  push:
    paths:
      - 'nsd/*'
jobs:
  build:
    name: Build & Push nsd Container
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Registry
        uses: actions/docker/login@86ff551d26008267bb89ac11198ba7f1d807b699
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - uses: actions/checkout@v1
      - name: Docker build & push
        uses: actions/docker/cli@86ff551d26008267bb89ac11198ba7f1d807b699
        with:
          args: build -t publicarray/nsd nsd && docker push publicarray/nsd
