name: nsd
on:
  push:
    paths:
      - 'nsd/*'
jobs:
  build:
    name: Build & Push nsd Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t publicarray/nsd nsd
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push publicarray/nsd
