name: nsd
on:
  push:
    paths:
      - 'nsd/*'
jobs:
  build:
    name: Build & Push nsd Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t publicarray/nsd nsd
      - uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: docker push publicarray/nsd
      - uses: azure/container-actions/docker-logout@master
