name: nsd
on:
  push:
    paths:
      - 'nsd/*'
jobs:
  build:
    name: Build & Push nsd Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t publicarray/nsd nsd

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.actor }}/dns-resolver-infra/nsd
          # tag_with_ref: true

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.actor }}/nsd
          # tag_with_ref: true
