on: push
name: Build & Push Containers
jobs:
  m13253-dohFilter:
    name: m13253-doh filter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: m13253-doh filter
      uses: actions/bin/filter@master
      with:
        args: issue_comment .*m13253.*
    - name: dnscrypt-wrapper filter
      uses: actions/bin/filter@master
      with:
        args: issue_comment .*dnscrypt.*
    - name: haproxy filter
      uses: actions/bin/filter@master
      with:
        args: issue_comment .*haproxy.*
    - name: unbound filter
      uses: actions/bin/filter@master
      with:
        args: issue_comment .*unbound.*
    - name: Docker Registry
      uses: actions/docker/login@86ff551d26008267bb89ac11198ba7f1d807b699
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Action for m13253-doh Docker
      uses: actions/docker/cli@86ff551d26008267bb89ac11198ba7f1d807b699
      with:
        args: docker build -t publicarray/m13253-doh m13253-doh && docker push publicarray/m13253-doh
    - name: Action for dnscrypt-wrapper Docker
      uses: actions/docker/cli@86ff551d26008267bb89ac11198ba7f1d807b699
      with:
        args: docker build -t publicarray/dnscrypt-wrapper dnscrypt-wrapper && docker
          push publicarray/dnscrypt-wrapper
    - name: Action for haproxy Docker
      uses: actions/docker/cli@86ff551d26008267bb89ac11198ba7f1d807b699
      with:
        args: docker build -t publicarray/haproxy haproxy && docker push publicarray/haproxy
    - name: Action for unbound Docker
      uses: actions/docker/cli@86ff551d26008267bb89ac11198ba7f1d807b699
      with:
        args: docker build -t publicarray/unbound unbound && docker push publicarray/unbound
