name: unbound
on:
  push:
    paths:
      - 'unbound/*'
jobs:
  build:
    name: Build & Push unbound Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t publicarray/unbound unbound
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push publicarray/unbound
