name: unbound Workflow
on:
  push:
    paths:
      - 'unbound/*'
jobs:
  build:
    name: Build & Push unbound Container
    runs-on: ubuntu-latest
    steps:
      - name: Docker Registry
        uses: actions/docker/login@86ff551d26008267bb89ac11198ba7f1d807b699
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Action for unbound Docker
        uses: actions/docker/cli@86ff551d26008267bb89ac11198ba7f1d807b699
        with:
          args: build -t publicarray/unbound unbound && docker push publicarray/unbound
